spring.application.name=SimuVivienda-Backend
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
#si quieres ejecutarlo en local

spring.datasource.url=jdbc:postgresql://localhost/Simu-vivienda
spring.datasource.username=postgres
spring.datasource.password=101004
server.port=8081